development:
  adapter: postgresql
  encoding: unicode
  host: localhost #db
  username: postgres
  password: 123456789
  pool: 5
  database: projeto_integrador

production:
  adapter: postgresql
  encoding: unicode
  username: projeto_integrador
  password: 123456789
  pool: 5
  database: projeto_integrador
