version: '3'
services:
  nginx:
   container_name: some-nginx
   image: nginx:1.13
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   depends_on:
   - api

  mysql:
   container_name: some-mysql
   image: mysql/mysql-server:5.7
   environment:
    MYSQL_DATABASE: projeto_integrador
    MYSQL_ROOT_PASSWORD: 123456789
    MYSQL_ROOT_HOST: '%'
   ports:
   - "3306:3306"
   restart: always

  api:
    restart: always
    build: ./server-api
    working_dir: /app
    volumes:
      - ./server-api:/app
      # - ~/.m2:/root/.m2
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - mysql
