version: '3'

volumes:
  db:

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: projeto_integrador
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_ROOT_HOST: '%'
    command:
      - "--character-set-server=utf8"
      - "--innodb_log_buffer_size=32M"
      - "--innodb_log_file_size=80M"
      - "--max_allowed_packet=8M"
      - "--explicit_defaults_for_timestamp"
    ports:
      - '33066:3306'
    volumes:
      - 'db:/var/lib/mysql'

  nginx:
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - api

  api:
    restart: always
    build: ./server-api
    working_dir: /server-api
    volumes:
      - ./server-api:/server-api
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - db
